CREATE TABLE IF NOT EXISTS ingestion_runs (
    run_id BIGSERIAL PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    status VARCHAR(50) NOT NULL,
    message TEXT
);

CREATE TABLE IF NOT EXISTS ingestion_files (
    file_id BIGSERIAL PRIMARY KEY,
    run_id BIGINT NOT NULL REFERENCES ingestion_runs(run_id),
    table_name VARCHAR(255) NOT NULL,
    source_file TEXT NOT NULL,
    source_sheet VARCHAR(255),
    row_count BIGINT NOT NULL DEFAULT 0,
    loaded_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(50) NOT NULL,
    message TEXT
);

CREATE TABLE IF NOT EXISTS raw_pay_cd (
    pay_dc_grp_type TEXT,
    entry_nm_1 TEXT,
    pay_dc_cd TEXT,
    pay_dc_nm TEXT,
    pay_dc_type TEXT,
    entry_nm_2 TEXT,
    source_file TEXT NOT NULL,
    source_sheet VARCHAR(255),
    loaded_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS raw_store_master (
    row_no TEXT,
    masked_stor_cd TEXT,
    maked_stor_nm TEXT,
    actual_sales_amt TEXT,
    campaign_sales_ratio TEXT,
    store_type TEXT,
    business_type TEXT,
    sido TEXT,
    region TEXT,
    shipment_center TEXT,
    store_area_pyeong TEXT,
    source_file TEXT NOT NULL,
    source_sheet VARCHAR(255),
    loaded_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS raw_daily_store_item_tmzon (
    masked_stor_cd TEXT,
    masked_stor_nm TEXT,
    item_nm TEXT,
    sale_dt TEXT,
    tmzon_div TEXT,
    item_cd TEXT,
    sale_qty TEXT,
    sale_amt TEXT,
    rtn_qty TEXT,
    rtn_amt TEXT,
    dc_amt TEXT,
    enuri_amt TEXT,
    vat_amt TEXT,
    actual_sale_amt TEXT,
    net_sale_amt TEXT,
    take_in_amt TEXT,
    take_in_vat_amt TEXT,
    take_out_amt TEXT,
    take_out_vat_amt TEXT,
    svc_fee_amt TEXT,
    svc_fee_vat_amt TEXT,
    reg_user_id TEXT,
    reg_date TEXT,
    upd_user_id TEXT,
    upd_date TEXT,
    source_file TEXT NOT NULL,
    source_sheet VARCHAR(255),
    loaded_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS raw_daily_store_cpi_tmzon (
    masked_stor_cd TEXT,
    masked_stor_nm TEXT,
    cpi_cd TEXT,
    cpi_nm TEXT,
    bill_cnt TEXT,
    qty_00 TEXT,
    qty_01 TEXT,
    qty_02 TEXT,
    qty_03 TEXT,
    qty_04 TEXT,
    qty_05 TEXT,
    qty_06 TEXT,
    qty_07 TEXT,
    qty_08 TEXT,
    qty_09 TEXT,
    qty_10 TEXT,
    qty_11 TEXT,
    qty_12 TEXT,
    qty_13 TEXT,
    qty_14 TEXT,
    qty_15 TEXT,
    qty_16 TEXT,
    qty_17 TEXT,
    qty_18 TEXT,
    qty_19 TEXT,
    qty_20 TEXT,
    qty_21 TEXT,
    qty_22 TEXT,
    qty_23 TEXT,
    dc_amt_00 TEXT,
    dc_amt_01 TEXT,
    dc_amt_02 TEXT,
    dc_amt_03 TEXT,
    dc_amt_04 TEXT,
    dc_amt_05 TEXT,
    dc_amt_06 TEXT,
    dc_amt_07 TEXT,
    dc_amt_08 TEXT,
    dc_amt_09 TEXT,
    dc_amt_10 TEXT,
    dc_amt_11 TEXT,
    dc_amt_12 TEXT,
    dc_amt_13 TEXT,
    dc_amt_14 TEXT,
    dc_amt_15 TEXT,
    dc_amt_16 TEXT,
    dc_amt_17 TEXT,
    dc_amt_18 TEXT,
    dc_amt_19 TEXT,
    dc_amt_20 TEXT,
    dc_amt_21 TEXT,
    dc_amt_22 TEXT,
    dc_amt_23 TEXT,
    act_amt_00 TEXT,
    act_amt_01 TEXT,
    act_amt_02 TEXT,
    act_amt_03 TEXT,
    act_amt_04 TEXT,
    act_amt_05 TEXT,
    act_amt_06 TEXT,
    act_amt_07 TEXT,
    act_amt_08 TEXT,
    act_amt_09 TEXT,
    act_amt_10 TEXT,
    act_amt_11 TEXT,
    act_amt_12 TEXT,
    act_amt_13 TEXT,
    act_amt_14 TEXT,
    act_amt_15 TEXT,
    act_amt_16 TEXT,
    act_amt_17 TEXT,
    act_amt_18 TEXT,
    act_amt_19 TEXT,
    act_amt_20 TEXT,
    act_amt_21 TEXT,
    act_amt_22 TEXT,
    act_amt_23 TEXT,
    source_file TEXT NOT NULL,
    source_sheet VARCHAR(255),
    loaded_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS raw_daily_store_pay_way (
    masked_stor_cd TEXT,
    masked_stor_nm TEXT,
    pay_way_cd_nm TEXT,
    pay_dtl_cd_nm TEXT,
    sale_dt TEXT,
    pay_way_cd TEXT,
    pay_dtl_cd TEXT,
    pay_amt TEXT,
    rec_amt TEXT,
    change_amt TEXT,
    rtn_pay_amt TEXT,
    rtn_rec_amt TEXT,
    rtn_change TEXT,
    etc_profit_amt TEXT,
    rtn_etc_profit_amt TEXT,
    cash_exchng_cpn TEXT,
    rtn_cash_exchng_cpn TEXT,
    reg_user_id TEXT,
    reg_date TEXT,
    upd_user_id TEXT,
    upd_date TEXT,
    source_file TEXT NOT NULL,
    source_sheet VARCHAR(255),
    loaded_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS raw_daily_store_item (
    masked_stor_cd TEXT,
    masked_stor_nm TEXT,
    item_nm TEXT,
    sale_dt TEXT,
    item_cd TEXT,
    item_tax_div TEXT,
    sale_qty TEXT,
    sale_amt TEXT,
    rtn_qty TEXT,
    rtn_amt TEXT,
    dc_amt TEXT,
    enuri_amt TEXT,
    vat_amt TEXT,
    actual_sale_amt TEXT,
    net_sale_amt TEXT,
    take_in_amt TEXT,
    take_in_vat_amt TEXT,
    take_out_amt TEXT,
    take_out_vat_amt TEXT,
    svc_fee_amt TEXT,
    svc_fee_vat_amt TEXT,
    reg_user_id TEXT,
    reg_date TEXT,
    upd_user_id TEXT,
    upd_date TEXT,
    source_file TEXT NOT NULL,
    source_sheet VARCHAR(255),
    loaded_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS raw_daily_store_online (
    masked_stor_cd TEXT,
    masked_stor_nm TEXT,
    sale_dt TEXT,
    tmzon_div TEXT,
    ho_chnl_cd TEXT,
    sales_org_nm TEXT,
    ho_chnl_div TEXT,
    ho_chnl_nm TEXT,
    sale_amt TEXT,
    ord_cnt TEXT,
    source_file TEXT NOT NULL,
    source_sheet VARCHAR(255),
    loaded_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS raw_workbook_rows (
    workbook_name TEXT NOT NULL,
    sheet_name VARCHAR(255) NOT NULL,
    row_index BIGINT NOT NULL,
    row_values_json JSONB NOT NULL,
    source_file TEXT NOT NULL,
    loaded_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ingestion_files_run_id ON ingestion_files(run_id);
CREATE INDEX IF NOT EXISTS idx_raw_daily_store_item_tmzon_sale_dt ON raw_daily_store_item_tmzon(sale_dt);
CREATE INDEX IF NOT EXISTS idx_raw_daily_store_item_sale_dt ON raw_daily_store_item(sale_dt);
CREATE INDEX IF NOT EXISTS idx_raw_daily_store_online_sale_dt ON raw_daily_store_online(sale_dt);
