CREATE TABLE IF NOT EXISTS raw_seoul_market_sales (
    id BIGSERIAL PRIMARY KEY,
    base_year INTEGER NOT NULL,
    base_quarter INTEGER NOT NULL,
    area_type_code TEXT,
    area_type_name TEXT,
    area_code TEXT,
    area_name TEXT NOT NULL,
    service_code TEXT,
    service_name TEXT NOT NULL,
    monthly_sales_amount NUMERIC,
    monthly_sales_count NUMERIC,
    weekend_sales_ratio NUMERIC,
    weekday_sales_amount NUMERIC,
    weekend_sales_amount NUMERIC,
    monday_sales_amount NUMERIC,
    tuesday_sales_amount NUMERIC,
    wednesday_sales_amount NUMERIC,
    thursday_sales_amount NUMERIC,
    friday_sales_amount NUMERIC,
    saturday_sales_amount NUMERIC,
    sunday_sales_amount NUMERIC,
    time_00_06_sales_amount NUMERIC,
    time_06_11_sales_amount NUMERIC,
    time_11_14_sales_amount NUMERIC,
    time_14_17_sales_amount NUMERIC,
    time_17_21_sales_amount NUMERIC,
    time_21_24_sales_amount NUMERIC,
    male_sales_amount NUMERIC,
    female_sales_amount NUMERIC,
    age10_sales_amount NUMERIC,
    age20_sales_amount NUMERIC,
    age30_sales_amount NUMERIC,
    age40_sales_amount NUMERIC,
    age50_sales_amount NUMERIC,
    age60_plus_sales_amount NUMERIC,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source_file TEXT
);

CREATE INDEX IF NOT EXISTS idx_raw_seoul_market_sales_scope
    ON raw_seoul_market_sales(base_year, base_quarter, area_name, service_name);

CREATE TABLE IF NOT EXISTS raw_seoul_market_floating_population (
    id BIGSERIAL PRIMARY KEY,
    base_year INTEGER NOT NULL,
    base_quarter INTEGER NOT NULL,
    area_type_code TEXT,
    area_type_name TEXT,
    area_code TEXT,
    area_name TEXT NOT NULL,
    total_population NUMERIC,
    male_population NUMERIC,
    female_population NUMERIC,
    age10_population NUMERIC,
    age20_population NUMERIC,
    age30_population NUMERIC,
    age40_population NUMERIC,
    age50_population NUMERIC,
    age60_plus_population NUMERIC,
    time_slot1_population NUMERIC,
    time_slot2_population NUMERIC,
    time_slot3_population NUMERIC,
    time_slot4_population NUMERIC,
    time_slot5_population NUMERIC,
    time_slot6_population NUMERIC,
    monday_population NUMERIC,
    tuesday_population NUMERIC,
    wednesday_population NUMERIC,
    thursday_population NUMERIC,
    friday_population NUMERIC,
    saturday_population NUMERIC,
    sunday_population NUMERIC,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source_file TEXT
);

CREATE INDEX IF NOT EXISTS idx_raw_seoul_market_floating_scope
    ON raw_seoul_market_floating_population(base_year, base_quarter, area_name);
