CREATE TABLE IF NOT EXISTS raw_production_extract (
    MASKED_STOR_CD TEXT,
    MASKED_STOR_NM TEXT,
    CMP_CD TEXT,
    PROD_DT TEXT,
    PROD_DGRE TEXT,
    ITEM_CD TEXT,
    ITEM_NM TEXT,
    PROD_QTY TEXT,
    SALE_PRC TEXT,
    ITEM_COST TEXT,
    PROD_QTY_2 TEXT,
    PROD_QTY_3 TEXT,
    REPROD_QTY TEXT,
    REG_USER_ID TEXT,
    REG_DATE TEXT,
    UPD_USER_ID TEXT,
    UPD_DATE TEXT,
    source_file TEXT NOT NULL,
    source_sheet VARCHAR(255),
    loaded_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS raw_order_extract (
    DLV_DT TEXT,
    MASKED_STOR_CD TEXT,
    MASKED_STOR_NM TEXT,
    ORD_GRP TEXT,
    ORD_GRP_NM TEXT,
    ORD_DGRE TEXT,
    ORD_DGRE_NM TEXT,
    ORD_TYPE TEXT,
    ORD_TYPE_NM TEXT,
    ITEM_CD TEXT,
    ITEM_NM TEXT,
    ERP_SEND_DT TEXT,
    ERP_WEB_ITEM_GRP TEXT,
    ERP_WEB_ITEM_GRP_NM TEXT,
    ORD_UNIT TEXT,
    ORD_NOQQTY TEXT,
    ORD_PRC TEXT,
    ORD_QTY TEXT,
    ORD_AMT TEXT,
    ORD_VAT TEXT,
    CONFRM_PRC TEXT,
    CONFRM_QTY TEXT,
    CONFRM_AMT TEXT,
    CONFRM_VAT TEXT,
    CONFRM_DC_AMT TEXT,
    AUTO_ORD_YN TEXT,
    ERP_DGRE TEXT,
    ERP_DGRE_NM TEXT,
    ORD_REC_QTY TEXT,
    source_file TEXT NOT NULL,
    source_sheet VARCHAR(255),
    loaded_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS raw_inventory_extract (
    MASKED_STOR_CD TEXT,
    MASKED_STOR_NM TEXT,
    CMP_CD TEXT,
    STOCK_DT TEXT,
    ITEM_CD TEXT,
    ITEM_NM TEXT,
    GI_QTY TEXT,
    ADD_SOUT_QTY TEXT,
    ADD_MOUT_QTY TEXT,
    INS_SOUT_QTY TEXT,
    INS_MOUT_QTY TEXT,
    MV_IN_QTY TEXT,
    MV_OUT_QTY TEXT,
    RTN_QTY TEXT,
    DISUSE_QTY TEXT,
    ADJ_QTY TEXT,
    SALE_QTY TEXT,
    PROD_IN_QTY TEXT,
    PROD_OUT_QTY TEXT,
    LAST_SALE_DT TEXT,
    COST TEXT,
    SALE_PRC TEXT,
    SALE_GRAM TEXT,
    REG_USER_ID TEXT,
    REG_DATE TEXT,
    UPD_USER_ID TEXT,
    UPD_DATE TEXT,
    STOCK_QTY TEXT,
    source_file TEXT NOT NULL,
    source_sheet VARCHAR(255),
    loaded_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_raw_production_extract_key
    ON raw_production_extract(MASKED_STOR_CD, PROD_DT, ITEM_CD);

CREATE INDEX IF NOT EXISTS idx_raw_order_extract_key
    ON raw_order_extract(MASKED_STOR_CD, DLV_DT, ITEM_CD);

CREATE INDEX IF NOT EXISTS idx_raw_inventory_extract_key
    ON raw_inventory_extract(MASKED_STOR_CD, STOCK_DT, ITEM_CD);
