name: br-korea-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi==0.115.0
      - uvicorn[standard]==0.30.6
      - pydantic==2.9.2
      - pydantic-settings==2.5.2
      - sqlalchemy
      - psycopg[binary]
      - psycopg
      - openpyxl
      - httpx
      - python-dotenv
      - pytest
