-- BR Korea 소스 시스템 원본 테이블 구조 (PostgreSQL 문법 기준)
-- 실제 적재 테이블은 db/migrations/의 raw_* 테이블을 사용한다.

CREATE TABLE "STOR_MST" (
  "ROW_NO"               TEXT,
  "MASKED_STOR_CD"       TEXT PRIMARY KEY,
  "MASKED_STOR_NM"       TEXT,
  "ACTUAL_SALES_AMT"     NUMERIC,
  "CAMPAIGN_SALES_RATIO" NUMERIC,
  "STORE_TYPE"           TEXT,
  "BUSINESS_TYPE"        TEXT,
  "SIDO"                 TEXT,
  "REGION"               TEXT,
  "SHIPMENT_CENTER"      TEXT,
  "STORE_AREA_PYEONG"    NUMERIC
);

CREATE TABLE "PAY_CD" (
  "PAY_WAY_CD"     TEXT,
  "PAY_WAY_NM"     TEXT,
  "PAY_DTL_CD"     TEXT,
  "PAY_DTL_NM"     TEXT,
  "PAY_DC_TYPE"    TEXT,
  "PAY_DC_TYPE_NM" TEXT,
  PRIMARY KEY ("PAY_WAY_CD", "PAY_DTL_CD")
);

CREATE TABLE "MST_TERM_COOP_CMP_PAY_DC" (
  "CMP_CD"                    TEXT,
  "PAY_DC_GRP_TYPE"           TEXT,
  "PAY_DC_CD"                 TEXT,
  "COOP_CMP_GRADE_CD"         TEXT,
  "START_DT"                  TEXT,
  "FNSH_DT"                   TEXT,
  "DC_APPLY_TRGT"             TEXT,
  "PAY_DC_METHD"              TEXT,
  "PAY_DC_VAL"                NUMERIC,
  "PAY_DC_AMT_STD_PAY_AMT"   NUMERIC,
  "PAY_DC_DEC_PNT_CALC_METHD" TEXT,
  "PAY_DC_CALC_DIGT_NO"       NUMERIC,
  "REG_USER_ID"               TEXT,
  "REG_DATE"                  TIMESTAMPTZ,
  "UPD_USER_ID"               TEXT,
  "UPD_DATE"                  TIMESTAMPTZ,
  "SALES_ORG_CD"              TEXT,
  "FUNC_ID"                   TEXT,
  "GRP_PRRTY"                 NUMERIC,
  "GRADE_PRRTY"               NUMERIC,
  "ITEM_DC_YN"                TEXT,
  "USE_YN"                    TEXT,
  "PAY_DC_AMT_MAX_PAY_AMT"    NUMERIC
);

CREATE TABLE "MST_TERM_COOP_CMP_DC_ITEM" (
  "CMP_CD"            TEXT,
  "PAY_DC_GRP_TYPE"   TEXT,
  "PAY_DC_CD"         TEXT,
  "COOP_CMP_GRADE_CD" TEXT,
  "START_DT"          TEXT,
  "ITEM_CD"           TEXT,
  "USE_YN"            TEXT,
  "REG_USER_ID"       TEXT,
  "REG_DATE"          TIMESTAMPTZ,
  "UPD_USER_ID"       TEXT,
  "UPD_DATE"          TIMESTAMPTZ,
  "SALES_ORG_CD"      TEXT,
  "ITEM_SEQ"          TEXT
);

CREATE TABLE "DAILY_STOR_CPI" (
  "CMP_CD"              TEXT,
  "SALE_DT"             TEXT,
  "MASKED_STOR_CD"      TEXT,
  "CPI_CD"              TEXT,
  "CPI_ADD_ACCUM_POINT" NUMERIC,
  "CPI_CUST_USE_POINT"  NUMERIC,
  "CPI_DC_QTY"          NUMERIC,
  "CPI_DC_AMT"          NUMERIC,
  "CPI_CUSTCNT"         NUMERIC,
  "CPI_BILLCNT"         NUMERIC,
  "TOTSALE_QTY"         NUMERIC,
  "TOTSALE_AMT"         NUMERIC,
  "TOTDC_AMT"           NUMERIC,
  "TOTACTUAL_SALE_AMT"  NUMERIC,
  "TOTVAT_AMT"          NUMERIC,
  "TOTNET_SALE_AMT"     NUMERIC,
  "TOTBILLCNT"          NUMERIC,
  "TOTCUSTCNT"          NUMERIC,
  "REG_USER_ID"         TEXT,
  "REG_DATE"            TIMESTAMPTZ,
  "UPD_USER_ID"         TEXT,
  "UPD_DATE"            TIMESTAMPTZ
);

CREATE TABLE "MST_PAY_DC_INFO" (
  "CMP_CD"               TEXT,
  "SALES_ORG_CD"         TEXT,
  "PAY_DC_TY_CD"         TEXT,
  "COOP_CD"              TEXT,
  "START_DT"             TEXT,
  "FNSH_DT"              TEXT,
  "PAY_DC_METHD"         TEXT,
  "MAT_LIST"             TEXT,
  "HQ_ALLOT_RATE"        NUMERIC,
  "STOR_ALLOT_RATE"      NUMERIC,
  "COOP_CMP_ALLOT_RATE"  NUMERIC,
  "HQ_VAT_YN"            TEXT,
  "ERP_YN"               TEXT,
  "USE_YN"               TEXT,
  "REG_USER_ID"          TEXT,
  "REG_DATE"             TIMESTAMPTZ,
  "UPD_USER_ID"          TEXT,
  "UPD_DATE"             TIMESTAMPTZ
);

CREATE TABLE "CPI_MST" (
  "CMP_CD"                         TEXT,
  "SALES_ORG_CD"                   TEXT,
  "CPI_CD"                         TEXT,
  "CPI_NM"                         TEXT,
  "RPST_CPI_CD"                    TEXT,
  "CPI_PRGRS_PRNCPL_TYPE"          TEXT,
  "CPI_KIND"                       TEXT,
  "CPI_TYPE"                       NUMERIC,
  "PRGRS_STATUS"                   TEXT,
  "PRRTY"                          NUMERIC,
  "START_DT"                       TEXT,
  "FNSH_DT"                        TEXT,
  "TRGT_CUST_TYPE"                 TEXT,
  "CPI_CUST_BNFT_TYPE"             TEXT,
  "ITEM_APPLY_METHD"               TEXT,
  "BASIC_HP_ACCUM_YN"              TEXT,
  "BASIC_HP_ACCUM_STD"             TEXT,
  "ADD_HP_ACCUM_TELECOM_DIV"       TEXT,
  "ADD_HP_ACCUM_TRGT_STD"          TEXT,
  "HP_ADD_ACCUM_RATE"              NUMERIC,
  "ADD_HP_ACCUM_CD_1"              TEXT,
  "ADD_HP_ACCUM_CD_2"              TEXT,
  "ADD_ACCUM_POSS_YN"              TEXT,
  "CUST_PAY_TYPE"                  TEXT,
  "TRGT_AMT_TYPE"                  TEXT,
  "TRGT_AMT"                       NUMERIC,
  "USE_YN"                         TEXT,
  "DUP_APPLY_YN"                   TEXT,
  "BASIC_RULE_EXCEP_YN"            TEXT,
  "TELECOM_COOP_DUP_PRMT_YN"       TEXT,
  "HQ_CPI_FIRST_YN"                TEXT,
  "CPI_INFO"                       TEXT,
  "REPT_YN"                        TEXT,
  "REPT_APPNT_TYPE"                TEXT,
  "REPT_DT"                        TEXT,
  "REPT_WEEK"                      TEXT,
  "STOR_SEL_TYPE"                  TEXT,
  "OFFER_ID"                       TEXT,
  "ADMT_METHD"                     TEXT,
  "HQ_DC_HP_MSHP_DRT_RATE"        NUMERIC,
  "HQ_DC_HP_MSHP_FRCS_RATE"       NUMERIC,
  "HQ_DC_HP_NMSHP_DRT_RATE"       NUMERIC,
  "HQ_DC_HP_NMSHP_FRCS_RATE"      NUMERIC,
  "HQ_ADD_ACCUM_DRT_RATE"         NUMERIC,
  "HQ_ADD_ACCUM_FRCS_RATE"        NUMERIC,
  "STOR_DC_HP_MSHP_DRT_RATE"      NUMERIC,
  "STOR_DC_HP_MSHP_FRCS_RATE"     NUMERIC,
  "STOR_DC_HP_NMSHP_DRT_RATE"     NUMERIC,
  "STOR_DC_HP_NMSHP_FRCS_RATE"    NUMERIC,
  "STOR_ADD_ACCUM_DRT_RATE"       NUMERIC,
  "STOR_ADD_ACCUM_FRCS_RATE"      NUMERIC,
  "COOP_CMP_DC_HP_MSHP_DRT_RATE"  NUMERIC,
  "COOP_CMP_DC_HP_MSHP_FRCS_RATE" NUMERIC,
  "COOP_CMP_DC_HP_NMSHP_DRT_RATE" NUMERIC,
  "COOP_CMP_DC_HP_NMSHP_FRCS_RATE" NUMERIC,
  "COOP_CMP_ADD_ACCUM_DRT_RATE"   NUMERIC,
  "COOP_CMP_ADD_ACCUM_FRCS_RATE"  NUMERIC,
  "HQ_FREE_GIFT_DRT_RATE"         NUMERIC,
  "HQ_FREE_GIFT_FRCS_RATE"        NUMERIC,
  "STOR_FREE_GIFT_DRT_RATE"       NUMERIC,
  "STOR_FREE_GIFT_FRCS_RATE"      NUMERIC,
  "COOP_CMP_FREE_GIFT_DRT_RATE"   NUMERIC,
  "COOP_CMP_FREE_GIFT_FRCS_RATE"  NUMERIC,
  "ALLOT_AMT_DEC_PNT_CALC_METHD"  TEXT,
  "ALLOT_AMT_CALC_DEC_PNT_DIGT_NO" NUMERIC,
  "QTY_LMT_YN"                    TEXT,
  "QTY_LMT_STD"                   TEXT,
  "LMT_QTY"                       NUMERIC,
  "HP_CUST_JOIN_LMT_YN"           TEXT,
  "HP_CUST_MAX_JOIN_CNT"          NUMERIC,
  "HP_CUST_JOIN_LMT_STD"          TEXT,
  "FREE_GIFT_PROVD_STD"           TEXT,
  "FREE_GIFT_STD_AMT"             NUMERIC,
  "FREE_GIFT_PROVD_QTY"           NUMERIC,
  "FREE_GIFT_ADD_SALE_YN"         TEXT,
  "CPI_EXPLN"                     TEXT,
  "REMAIN_LTTR_WARN_QTY"          NUMERIC,
  "CUST_FACE_RSCE_FILE_DIV"       TEXT,
  "CUST_FACE_RSCE_FILE_NM"        TEXT,
  "CUST_FACE_RSCE_FILE_ID"        TEXT,
  "VALID_TERM_START_DT"           TEXT,
  "VALID_TERM_FNSH_DT"            TEXT,
  "SCOPE_YN"                      TEXT,
  "LTTR_PRT_STD"                  TEXT,
  "REG_USER_ID"                   TEXT,
  "REG_DATE"                      TIMESTAMPTZ,
  "UPD_USER_ID"                   TEXT,
  "UPD_DATE"                      TIMESTAMPTZ,
  "PROMO_AGREE_CD"                TEXT,
  "STAMP_QTY"                     NUMERIC,
  "SOUND_FILE_DIV"                TEXT,
  "SOUND_FILE_NM"                 TEXT,
  "SOUND_FILE_ID"                 TEXT,
  "TTS_DSCRP"                     TEXT,
  "SOUND_FILE_PLAY_CHK_PNT"       TEXT,
  "JOIN_QUSTN_YN"                 TEXT,
  "ITEM_DUP_PRMT_YN"              TEXT,
  "LTTR_MULTI_PRT_YN"             TEXT,
  "CPI_DC_PAY_WAY"                TEXT,
  "CPI_BILL_NM"                   TEXT,
  "QTY_LIMIT_MSG"                 TEXT,
  "HP_CUST_LVL"                   TEXT,
  "DC_NOADM_PASS_YN"              TEXT,
  "BR31DAY_YN"                    TEXT,
  "HPY_CPN_USE_YN"                TEXT,
  "TERM_COOP_DUP_PRMT_YN"         TEXT,
  "KIOSK_DIV"                     TEXT,
  "MOBILE_DUP_YN"                 TEXT,
  "REF_FILLER"                    TEXT,
  "LSM_DIV"                       TEXT,
  "CLEARANCE_YN"                  TEXT,
  "WEATHER_DIV"                   TEXT,
  "BRAPP_CPN_USE_YN"              TEXT
);

CREATE TABLE "CPI_ITEM_GRP_MNG" (
  "CMP_CD"           TEXT,
  "SALES_ORG_CD"     TEXT,
  "CPI_CD"           TEXT,
  "CPI_ITEM_GRP_CD"  TEXT,
  "CPI_ITEM_GRP_NM"  TEXT,
  "CPI_COND_TYPE"    TEXT,
  "QTY_AMT"          NUMERIC,
  "CPI_DC_TYPE"      TEXT,
  "DC_RATE_QTY_AMT"  NUMERIC,
  "NOTE"             TEXT,
  "REG_USER_ID"      TEXT,
  "REG_DATE"         TIMESTAMPTZ,
  "UPD_USER_ID"      TEXT,
  "UPD_DATE"         TIMESTAMPTZ,
  "MAX_DC_AMT"       NUMERIC,
  "USE_YN"           TEXT
);

CREATE TABLE "CPI_ITEM_MNG" (
  "CMP_CD"          TEXT,
  "SALES_ORG_CD"    TEXT,
  "CPI_CD"          TEXT,
  "CPI_ITEM_GRP_CD" TEXT,
  "ITEM_LVL"        TEXT,
  "ITEM_CD"         TEXT,
  "CPI_DC_TYPE"     TEXT,
  "DC_RATE_AMT"     NUMERIC,
  "USE_YN"          TEXT,
  "REG_USER_ID"     TEXT,
  "REG_DATE"        TIMESTAMPTZ,
  "UPD_USER_ID"     TEXT,
  "UPD_DATE"        TIMESTAMPTZ
);

CREATE TABLE "ORD_DTL" (
  "CMP_CD"          TEXT,
  "DLV_DT"          TEXT,
  "STOR_CD"         TEXT,
  "ORD_GRP"         TEXT,
  "ORD_DGRE"        TEXT,
  "ORD_TYPE"        TEXT,
  "ITEM_CD"         TEXT,
  "ERP_SEND_DT"     TEXT,
  "ERP_WEB_ITEM_GRP" TEXT,
  "ORD_UNIT"        TEXT,
  "ORD_NOQQTY"      NUMERIC,
  "ORD_PRC"         NUMERIC,
  "ORD_QTY"         NUMERIC,
  "ORD_AMT"         NUMERIC,
  "ORD_VAT"         NUMERIC,
  "CONFRM_PRC"      NUMERIC,
  "CONFRM_QTY"      NUMERIC,
  "CONFRM_AMT"      NUMERIC,
  "CONFRM_VAT"      NUMERIC,
  "CONFRM_DC_AMT"   NUMERIC,
  "AUTO_ORD_YN"     TEXT,
  "ERP_DGRE"        TEXT,
  "REG_USER_ID"     TEXT,
  "REG_DATE"        TIMESTAMPTZ,
  "UPD_USER_ID"     TEXT,
  "UPD_DATE"        TIMESTAMPTZ,
  "ORD_REC_QTY"     NUMERIC
);

CREATE TABLE "DAILY_STOR_ITEM_TMZON" (
  "MASKED_STOR_CD"    TEXT,
  "MASKED_STOR_NM"    TEXT,
  "ITEM_NM"           TEXT,
  "SALE_DT"           TEXT,
  "TMZON_DIV"         TEXT,
  "ITEM_CD"           TEXT,
  "SALE_QTY"          NUMERIC,
  "SALE_AMT"          NUMERIC,
  "RTN_QTY"           NUMERIC,
  "RTN_AMT"           NUMERIC,
  "DC_AMT"            NUMERIC,
  "ENURI_AMT"         NUMERIC,
  "VAT_AMT"           NUMERIC,
  "ACTUAL_SALE_AMT"   NUMERIC,
  "NET_SALE_AMT"      NUMERIC,
  "TAKE_IN_AMT"       NUMERIC,
  "TAKE_IN_VAT_AMT"   NUMERIC,
  "TAKE_OUT_AMT"      NUMERIC,
  "TAKE_OUT_VAT_AMT"  NUMERIC,
  "SVC_FEE_AMT"       NUMERIC,
  "SVC_FEE_VAT_AMT"   NUMERIC,
  "REG_USER_ID"       TEXT,
  "REG_DATE"          TIMESTAMPTZ,
  "UPD_USER_ID"       TEXT,
  "UPD_DATE"          TIMESTAMPTZ
);

CREATE TABLE "DAILY_STOR_PAY_WAY" (
  "CMP_CD"              TEXT,
  "SALE_DT"             TEXT,
  "MASKED_STOR_CD"      TEXT,
  "PAY_WAY_CD"          TEXT,
  "PAY_DTL_CD"          TEXT,
  "PAY_AMT"             NUMERIC,
  "REC_AMT"             NUMERIC,
  "CHANGE"              NUMERIC,
  "RTN_PAY_AMT"         NUMERIC,
  "RTN_REC_AMT"         NUMERIC,
  "RTN_CHANGE"          NUMERIC,
  "ETC_PROFIT_AMT"      NUMERIC,
  "RTN_ETC_PROFIT_AMT"  NUMERIC,
  "CASH_EXCHNG_CPN"     NUMERIC,
  "RTN_CASH_EXCHNG_CPN" NUMERIC,
  "REG_USER_ID"         TEXT,
  "REG_DATE"            TIMESTAMPTZ,
  "UPD_USER_ID"         TEXT,
  "UPD_DATE"            TIMESTAMPTZ
);

CREATE TABLE "DAILY_STOR_ITEM" (
  "CMP_CD"           TEXT,
  "SALE_DT"          TEXT,
  "MASKED_STOR_CD"   TEXT,
  "ITEM_CD"          TEXT,
  "ITEM_TAX_DIV"     TEXT,
  "SALE_QTY"         NUMERIC,
  "SALE_AMT"         NUMERIC,
  "RTN_QTY"          NUMERIC,
  "RTN_AMT"          NUMERIC,
  "DC_AMT"           NUMERIC,
  "ENURI_AMT"        NUMERIC,
  "VAT_AMT"          NUMERIC,
  "ACTUAL_SALE_AMT"  NUMERIC,
  "NET_SALE_AMT"     NUMERIC,
  "TAKE_IN_AMT"      NUMERIC,
  "TAKE_IN_VAT_AMT"  NUMERIC,
  "TAKE_OUT_AMT"     NUMERIC,
  "TAKE_OUT_VAT_AMT" NUMERIC,
  "SVC_FEE_AMT"      NUMERIC,
  "SVC_FEE_VAT_AMT"  NUMERIC,
  "REG_USER_ID"      TEXT,
  "REG_DATE"         TIMESTAMPTZ,
  "UPD_USER_ID"      TEXT,
  "UPD_DATE"         TIMESTAMPTZ
);

CREATE TABLE "DAILY_STOR_CHL_TMZON" (
  "MASKED_STOR_CD" TEXT,
  "MASKED_STOR_NM" TEXT,
  "SALE_DT"        TEXT,
  "TMZON_DIV"      TEXT,
  "HO_CHNL_CD"     TEXT,
  "SALES_ORG_NM"   TEXT,
  "HO_CHNL_DIV"    TEXT,
  "HO_CHNL_NM"     TEXT,
  "SALE_AMT"       NUMERIC,
  "ORD_CNT"        NUMERIC
);

CREATE TABLE "PROD_DTL" (
  "CMP_CD"         TEXT,
  "PROD_DT"        TEXT,
  "MASKED_STOR_CD" TEXT,
  "PROD_DGRE"      TEXT,
  "ITEM_CD"        TEXT,
  "PROD_QTY"       NUMERIC,
  "SALE_PRC"       NUMERIC,
  "ITEM_COST"      NUMERIC,
  "PROD_QTY_2"     NUMERIC,
  "PROD_QTY_3"     NUMERIC,
  "REPROD_QTY"     NUMERIC,
  "REG_USER_ID"    TEXT,
  "REG_DATE"       TIMESTAMPTZ,
  "UPD_USER_ID"    TEXT,
  "UPD_DATE"       TIMESTAMPTZ
);

CREATE TABLE "SPL_DAY_STOCK_DTL" (
  "CMP_CD"          TEXT,
  "STOCK_DT"        TEXT,
  "MASKED_STOR_CD"  TEXT,
  "RECDIS_LOC"      TEXT,
  "ITEM_CD"         TEXT,
  "BAR_CD"          TEXT,
  "GI_QTY"          NUMERIC,
  "GO_QTY"          NUMERIC,
  "GO_CANCEL_QTY"   NUMERIC,
  "DSPS_QTY"        NUMERIC,
  "RTN_QTY"         NUMERIC,
  "ADJ_QTY"         NUMERIC,
  "MOVE_GI_QTY"     NUMERIC,
  "MOVE_GO_QTY"     NUMERIC,
  "CUST_RTN_QTY"    NUMERIC,
  "ADD_FOUT_QTY"    NUMERIC,
  "ADD_UNDLV_QTY"   NUMERIC,
  "ISPCTN_FOUT_QTY" NUMERIC,
  "ISPCTN_UNDLV_QTY" NUMERIC,
  "SALE_QTY"        NUMERIC,
  "DISTBT_EXPIRE"   TEXT,
  "REG_USER_ID"     TEXT,
  "REG_DATE"        TIMESTAMPTZ,
  "UPD_USER_ID"     TEXT,
  "UPD_DATE"        TIMESTAMPTZ,
  "NO_SALE_QTY"     NUMERIC
);

ALTER TABLE "ORD_DTL"            ADD FOREIGN KEY ("STOR_CD")                    REFERENCES "STOR_MST" ("MASKED_STOR_CD");
ALTER TABLE "DAILY_STOR_ITEM_TMZON" ADD FOREIGN KEY ("MASKED_STOR_CD")          REFERENCES "STOR_MST" ("MASKED_STOR_CD");
ALTER TABLE "DAILY_STOR_CPI"     ADD FOREIGN KEY ("MASKED_STOR_CD")             REFERENCES "STOR_MST" ("MASKED_STOR_CD");
ALTER TABLE "DAILY_STOR_PAY_WAY" ADD FOREIGN KEY ("MASKED_STOR_CD")             REFERENCES "STOR_MST" ("MASKED_STOR_CD");
ALTER TABLE "DAILY_STOR_ITEM"    ADD FOREIGN KEY ("MASKED_STOR_CD")             REFERENCES "STOR_MST" ("MASKED_STOR_CD");
ALTER TABLE "DAILY_STOR_CHL_TMZON" ADD FOREIGN KEY ("MASKED_STOR_CD")          REFERENCES "STOR_MST" ("MASKED_STOR_CD");
ALTER TABLE "PROD_DTL"           ADD FOREIGN KEY ("MASKED_STOR_CD")             REFERENCES "STOR_MST" ("MASKED_STOR_CD");
ALTER TABLE "SPL_DAY_STOCK_DTL"  ADD FOREIGN KEY ("MASKED_STOR_CD")             REFERENCES "STOR_MST" ("MASKED_STOR_CD");
ALTER TABLE "DAILY_STOR_PAY_WAY" ADD FOREIGN KEY ("PAY_WAY_CD", "PAY_DTL_CD")  REFERENCES "PAY_CD"   ("PAY_WAY_CD", "PAY_DTL_CD");
ALTER TABLE "MST_PAY_DC_INFO"    ADD FOREIGN KEY ("PAY_DC_TY_CD")               REFERENCES "PAY_CD"   ("PAY_DTL_CD");
ALTER TABLE "MST_TERM_COOP_CMP_PAY_DC" ADD FOREIGN KEY ("PAY_DC_GRP_TYPE", "PAY_DC_CD") REFERENCES "PAY_CD" ("PAY_WAY_CD", "PAY_DTL_CD");
ALTER TABLE "MST_TERM_COOP_CMP_DC_ITEM" ADD FOREIGN KEY ("PAY_DC_GRP_TYPE", "PAY_DC_CD", "COOP_CMP_GRADE_CD", "START_DT") REFERENCES "MST_TERM_COOP_CMP_PAY_DC" ("PAY_DC_GRP_TYPE", "PAY_DC_CD", "COOP_CMP_GRADE_CD", "START_DT");
ALTER TABLE "DAILY_STOR_CPI"     ADD FOREIGN KEY ("CPI_CD")                     REFERENCES "CPI_MST"  ("CPI_CD");
ALTER TABLE "CPI_ITEM_GRP_MNG"   ADD FOREIGN KEY ("CPI_CD")                     REFERENCES "CPI_MST"  ("CPI_CD");
ALTER TABLE "CPI_ITEM_MNG"       ADD FOREIGN KEY ("CPI_CD", "CPI_ITEM_GRP_CD")  REFERENCES "CPI_ITEM_GRP_MNG" ("CPI_CD", "CPI_ITEM_GRP_CD");